# GitHub Sponsors
github: [nagcas]

# Altri canali di supporto
# ko_fi: nagcas   # <-- se hai un account Ko-fi
# buy_me_a_coffee: nagcas  # <-- se hai un account Buy Me a Coffee

# URL personalizzato (esempio PayPal)
custom: ["https://paypal.me/magcas"]
